language: python
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8.2
    env: TOXENV=py38
  - python: pypy
    env: TOXENV=pypy
  - python: pypy3
    env: TOXENV=pypy3
install:
  - pip install tox
  - pip install mock
script:
  - tox
deploy:
  provider: pypi
  user: Mahmoud.Abdelkader
  password:
    secure: OhjlsFN3zIHqW6PlpSanlHhJ3Bx6jIAPZM6jObMeA4yXp74NCdzpPBS/Drdj0dnKXj5edkzUQ4iC72Eyx5vmHvq0yHIM49FvfEliJ5oihQGgqZufqA6EjaVSvRaRh7ZERcwGKzbPpCGulh55V1bURDFOTXwk2n9X4/xmIyX3v7w=
  on:
    python: 3.8
    tags: true
    repo: mahmoudimus/nose-timer
